 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/harvests", type: :request do
  
  # Harvest. As you add validations to Harvest, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Harvest.create! valid_attributes
      get harvests_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      harvest = Harvest.create! valid_attributes
      get harvest_url(harvest)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_harvest_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      harvest = Harvest.create! valid_attributes
      get edit_harvest_url(harvest)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Harvest" do
        expect {
          post harvests_url, params: { harvest: valid_attributes }
        }.to change(Harvest, :count).by(1)
      end

      it "redirects to the created harvest" do
        post harvests_url, params: { harvest: valid_attributes }
        expect(response).to redirect_to(harvest_url(Harvest.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Harvest" do
        expect {
          post harvests_url, params: { harvest: invalid_attributes }
        }.to change(Harvest, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post harvests_url, params: { harvest: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested harvest" do
        harvest = Harvest.create! valid_attributes
        patch harvest_url(harvest), params: { harvest: new_attributes }
        harvest.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the harvest" do
        harvest = Harvest.create! valid_attributes
        patch harvest_url(harvest), params: { harvest: new_attributes }
        harvest.reload
        expect(response).to redirect_to(harvest_url(harvest))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        harvest = Harvest.create! valid_attributes
        patch harvest_url(harvest), params: { harvest: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested harvest" do
      harvest = Harvest.create! valid_attributes
      expect {
        delete harvest_url(harvest)
      }.to change(Harvest, :count).by(-1)
    end

    it "redirects to the harvests list" do
      harvest = Harvest.create! valid_attributes
      delete harvest_url(harvest)
      expect(response).to redirect_to(harvests_url)
    end
  end
end
